### ISSUE TITLE
thrown errors in RStudio

### ISSUE THREAD

**Issue by krzbar** [venelin/PCMBaseCpp#1] opened 2019-10-16 12:16 UTC
a MWE:
library(TreeSim)
library(PCMBase)
library(PCMBaseCpp)
modelBM <- PCMBase::PCM(model = "BM", k = 1)
phyltree<-TreeSim::sim.bd.taxa(n=5,numbsim=1,lambda=1,mu=0)[[1]]
phyltree$root.edge<-NULL
mTraits<-matrix(0,ncol=1,nrow=5)
loglik_PCMBase<-PCMBase::PCMLik(t(mTraits), phyltree, modelBM)
loglik_PCMBase
loglik_PCMBaseCpp_PCMLik<-PCMBase::PCMLik(t(mTraits), phyltree, modelBM, metaI = PCMBaseCpp::PCMInfoCpp)

On Linux (R 3.6.1, openSUSE Leap 42.3) both loglik_PCMBase and loglik_PCMBaseCpp_PCMLik end up as NA and in both cases a warning appears (as desired).

However, in RStudio on Windows (R 3.6.0 on x86_64-w64-mingw32/x64 (64-bit), RStudio 1.1.456, Windows 10 Education version 1809) loglik_PCMBase ends up as NA with a warning thrown but calling PCMBase::PCMLik(t(mTraits), phyltree, modelBM, metaI = PCMBaseCpp::PCMInfoCpp) results in an error thrown by the C++ code: 
terminate called after throwing an instance of 'std::logic_error' ...
and RStudio needs to be restarted (see attached screen shot)
![MWE_error4](https://user-images.githubusercontent.com/27812821/66918398-ceb9c400-f00e-11e9-9d74-8315762ffb2d.png)

**Comment by venelin** [comment] 2019-10-16 12:32
From the above I cannot deduce whether the problem is Windows or RStudio-related.

What happens, if the test is run on a Windows machine from the R command prompt, i.e. outside RStudio? 
Also, could you provide the RStudio version number also for the Linux machine?

**Comment by krzbar** [comment] 2019-10-16 14:51
No RStudio was used on Linux, only command line R.
![MWE_error5](https://user-images.githubusercontent.com/27812821/66930571-54943a00-f024-11e9-8b5e-385caa637465.png)


loglik_PCMBase ends up as NA with a warning thrown but calling PCMBase::PCMLik(t(mTraits), phyltree, modelBM, metaI = PCMBaseCpp::PCMInfoCpp) results in R freezing, lot of CPU% usage, and having to be killed through the Task Manager

**Comment by venelin** [comment] 2019-10-17 15:44
Not sure, but the above screenshot seems like another graphcial R-environment (RGui) and not the standard text-mode R-interface (i.e. the one available from a terminal). 

PCMBaseCpp throws std::logic_error exception whenever, during a likelihood calculation, it detects a numerical problem, such as a nearly singular variance covariance transition matrix for a given edge, or a defective matrix H (selection strength parameter of an OU process). Such logic_error exceptions are caught and handled in the R-code of the PCMBase package using the `try(..., silent = TRUE)` construct.

It seems that this exception handling mechanism fails on Windows, but works well on all other tested platforms. Hence, I would assume that this is problem at the interface of R and Rcpp specific for Windows OS -- I recommend opening an issue about it on the Rcpp mailing list. 

One possible work-around is to set to 0 the following runtime options: 

```
options(PCMBase.Threshold.EV = 0)
options(PCMBase.Threshold.SV = 0)
``` 

This would prevent PCMBaseCpp from throwing an exception, because it eliminates the check for singularity. I would still not recommend this, because it may result in serious numerical problems during model inference.

**Comment by krzbar** [comment] 2019-10-18 10:45
I agree that this is a interface R and Rcpp problem on Windows. However, it essentially makes PCMBaseCpp not usable as a computational engine for parameter estimation for Windows users-as any search procedure (also PCMFit) can easily fall into such a singularity when exploring the parameter space. 

Setting the runtime options to 0 does not help. This is as in the setup, the covariance matrix was exactly singular. It will work if the covariance matrix is nearly singular (see screenshots). Setting the thresholds negative causes another type of error, i.e. they are forbidden to be negative.

One suggestion is that inside PCMBaseCpp it could be checked if lesser-equal than thresholds then do computations and not lesser than. Setting the thresholds to 0, would, then of course put the responsibility on the caller to make sure that the likelihood is sane? 

Alternatively, what about PCMBaseCpp returning Infinity or -Infinity in such a situation instead of throwing an exception and then PCMBase throws the exception?
![MWE_error6_options0](https://user-images.githubusercontent.com/27812821/67088284-482eef00-f194-11e9-846a-9d09d7e9c919.png)
![MWE_error6_optionsNearlySingular_2](https://user-images.githubusercontent.com/27812821/67088298-50872a00-f194-11e9-9a7a-2fd8fc8f3ac6.png)
![MWE_error6_optionsNeg](https://user-images.githubusercontent.com/27812821/67088302-53821a80-f194-11e9-8dec-af0f266660e3.png)

**Comment by venelin** [comment] 2019-10-18 12:35
> However, it essentially makes PCMBaseCpp not usable as a computational engine for parameter estimation for Windows users-as any search procedure (also PCMFit) can easily fall into such a singularity when exploring the parameter space. 

> Setting the runtime options to 0 does not help. This is as in the setup, the covariance matrix was exactly singular. It will work if the covariance matrix is nearly singular (see screenshots). Setting the thresholds negative causes another type of error, i.e. they are forbidden to be negative.

I agree. 

> One suggestion is that inside PCMBaseCpp it could be checked if lesser-equal than thresholds then do computations and not lesser than. Setting the thresholds to 0, would, then of course put the responsibility on the caller to make sure that the likelihood is sane?

This would prevent the exception from throwing but, as you already mentioned above, it would result in numerical issues during parameter space exploration. I would therefore abstain from it.

> Alternatively, what about PCMBaseCpp returning Infinity or -Infinity in such a situation instead of throwing an exception and then PCMBase throws the exception?

This is a considerable although quite implementation-heavy approach. 

Meanwhile I've open an issue regarding this on the Rcpp list: https://github.com/RcppCore/Rcpp/issues/1001#issue-509047134

Venelin

**Comment by krzbar** [comment] 2019-10-18 19:19
>This would prevent the exception from throwing but, as you already mentioned above, 
> it would result in numerical issues during parameter space exploration. 
> I would therefore abstain from it.
Actually this should not be such a worry (caveat below).
Assume that you have <=. Then, if someone actively sets these options to 0, then they are aware of the implications and will safeguard if the outputted likelihood makes sense. One will nearly always get a loglikelihood that is a negative number of extremely big magnitude-indicating a bad place in the search space that one should jump out of. Same reaction if an exception is thrown.
Very rarely one will get a huge loglikelihood of positive magnitude-this only if there is little variability in the data. In this case the result makes sense, but again this has to be taken care of. 
As long as the person doing the call is aware that they need to check the output and react (by e.g. setting the result to a minimal acceptable level and/or jumping to another part of the parameter space), then no issues will be caused. If someone, sets the options to 0, then I think one can assume that they are aware of the implications.
Caveat: I am not sure what PCMBaseCpp does next, whether actually having a 0 determinant covariance matrix (nearly 0 seemed to go OK) will allow computations to proceed with some strange number, or cause some other exception thrown later and same result of R crashing on Windows.

**Comment by venelin** [comment] 2019-10-21 09:20
I implemented the fix handling the exception on the C++ level. Please, install the head (master branch) from github and repeat the test on Windows.

**Comment by krzbar** [comment] 2019-11-05 09:11
Can one replicate this error on a Linux machine? Could you provide a MWE for this?
Newest version on Windows :

![MWE_error8_newPCMBaseCpp0optionSing_2](https://user-images.githubusercontent.com/27812821/68193801-b1439e80-ffab-11e9-8d0f-3bd65e2c78df.png)
![MWE_error8_newPCMBaseCppNo0optionSing](https://user-images.githubusercontent.com/27812821/68193815-b9034300-ffab-11e9-9fcb-6d74c47febf0.png)
![MWE_error8_newPCMBaseCpp0optionNonSing](https://user-images.githubusercontent.com/27812821/68193822-bef92400-ffab-11e9-9da7-aca30ec60153.png)
![MWE_error8_newPCMBaseCppNo0optionSing](https://user-images.githubusercontent.com/27812821/68193844-ce786d00-ffab-11e9-963b-1758e1ac7a89.png)

**Comment by venelin** [comment] 2019-11-05 10:40
I tested on linux and it seems to happen when the -fopenmp compiler option is on but not otherwise. It might behave differently depending on the compiler. Now, i've disabled this option and everything works as it should on my osx and linux environments. Could you test on Windows and post a screenshot?

**Comment by krzbar** [comment] 2019-11-05 11:13
Seems to work now. When options not set NA is returned, when set some ridiculous likelihood.

![MWE_error9_newPCMBaseCpp0optionNonSing](https://user-images.githubusercontent.com/27812821/68203210-371c1580-ffbd-11e9-99cc-41705fa63c17.png)
![MWE_error9_newPCMBaseCpp0optionSing](https://user-images.githubusercontent.com/27812821/68203211-371c1580-ffbd-11e9-9458-68a11f726917.png)
![MWE_error9_newPCMBaseCppNo0optionNonSing](https://user-images.githubusercontent.com/27812821/68203212-371c1580-ffbd-11e9-8a3b-44d0d4514c9b.png)
![MWE_error9_newPCMBaseCppNo0optionSing](https://user-images.githubusercontent.com/27812821/68203213-37b4ac00-ffbd-11e9-918a-6cdfa0de0a65.png)

**Comment by venelin** [comment] 2019-11-05 13:05
So far this confirms my suspicion. Now I've disabled the try-catch statement on the C++ and the -fopenmp compiler flag is still disabled. Please, could you test one last time on Windows. If it works that would mean that the only cause of the problem has been the -fopenmp option.

Cheers, 
Venelin

**Comment by krzbar** [comment] 2019-11-06 11:07
Seems to work

![MWE_error10_newPCMBaseCpp0optionNonSing](https://user-images.githubusercontent.com/27812821/68293332-a2c9b580-0085-11ea-80b9-a8a329b3b3c2.png)
![MWE_error10_newPCMBaseCpp0optionSing](https://user-images.githubusercontent.com/27812821/68293333-a2c9b580-0085-11ea-884a-e755b60c2044.png)
![MWE_error10_newPCMBaseCppNo0optionNonSing](https://user-images.githubusercontent.com/27812821/68293335-a2c9b580-0085-11ea-9f75-a96082d9c857.png)
![MWE_error10_newPCMBaseCppNo0optionSing](https://user-images.githubusercontent.com/27812821/68293336-a2c9b580-0085-11ea-9fc1-cc6925503010.png)

**Comment by venelin** [comment] 2019-11-12 13:12
I've implemented a fix in the SPLITT library and uploaded PCMBaseCpp_v0.1.6 to CRAN. Let me know if there are still problems. Now closing the issue.

**Closed as completed by venelin** 2019-11-12 13:12 UTC
Labels: enhancement, question
